#!/usr/bin/env bash
# Usage: cfenv environment-file-read <file>
set -e
[ -n "$CFENV_DEBUG" ] && set -x

ENVIRONMENT_FILE="$1"

if [ -e "$ENVIRONMENT_FILE" ]; then
  # Read the first non-whitespace word from the specified environment file.
  # Be careful not to load it whole in case there's something crazy in it.
  IFS="${IFS}"$'\r'
  words=( $(cut -b 1-1024 "$ENVIRONMENT_FILE") )
  environment="${words[0]}"

  if [ -n "$environment" ]; then
    echo "$environment"
    exit
  fi
fi

exit 1
