#!/usr/bin/env bash
# Summary: List all Cloud Foundry environments that contain the given executable
# Usage: cfenv whence [--path] <command>

set -e
[ -n "$CFENV_DEBUG" ] && set -x

# Provide cfenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec cfenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  cfenv-environments --bare | while read environment; do
    path="$(cfenv-prefix "$environment")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$environment"
    fi
  done
}

CFENV_COMMAND="$1"
if [ -z "$CFENV_COMMAND" ]; then
  cfenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$CFENV_COMMAND")"
[ -n "$result" ] && echo "$result"
