#!/usr/bin/env bash
# Summary: Display prefix for a Cloud Foundry environment
# Usage: cfenv prefix [<environment>]
#
# Displays the directory where a Cloud Foundry environment is installed. If no
# environment is given, `cfenv prefix' displays the location of the
# currently selected environment.

set -e
[ -n "$CFENV_DEBUG" ] && set -x

# Provide cfenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec cfenv-environments --bare
fi

if [ -n "$1" ]; then
  export CFENV_ENVIRONMENT="$1"
elif [ -z "$CFENV_ENVIRONMENT" ]; then
  CFENV_ENVIRONMENT="$(cfenv-environment-name)"
fi

if [ "$CFENV_ENVIRONMENT" = "system" ]; then
  if CF_PATH="$(cfenv-which cf 2>/dev/null)"; then
    CF_PATH="${CF_PATH%/*}"
    echo "${CF_PATH%/bin}"
    exit
  else
    echo "cfenv: system environment not found in PATH" >&2
    exit 1
  fi
fi

CFENV_PREFIX_PATH="${CFENV_ROOT}/environments/${CFENV_ENVIRONMENT}"
if [ ! -d "$CFENV_PREFIX_PATH" ]; then
  echo "cfenv: environment \`${CFENV_ENVIRONMENT}' not installed" >&2
  exit 1
fi

echo "$CFENV_PREFIX_PATH"
