#!/usr/bin/env bash
# Summary: Detect the file that sets the current cfenv environment
set -e
[ -n "$CFENV_DEBUG" ] && set -x

find_local_environment_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.cf-environment" ]; then
      echo "${root}/.cf-environment"
      exit
    elif [ -e "${root}/.cfenv-environment" ]; then
      echo "${root}/.cfenv-environment"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_environment_file "$CFENV_DIR"
[ "$CFENV_DIR" = "$PWD" ] || find_local_environment_file "$PWD"

global_environment_file="${CFENV_ROOT}/environment"

if [ -e "$global_environment_file" ]; then
  echo "$global_environment_file"
elif [ -e "${CFENV_ROOT}/global" ]; then
  echo "${CFENV_ROOT}/global"
elif [ -e "${CFENV_ROOT}/default" ]; then
  echo "${CFENV_ROOT}/default"
else
  echo "$global_environment_file"
fi
