#!/usr/bin/env bash
# Summary: Explain how the current Cloud Foundry environment is set
set -e
[ -n "$CFENV_DEBUG" ] && set -x

if [ -n "$CFENV_ENVIRONMENT" ]; then
  echo "CFENV_ENVIRONMENT environment variable"
else
  cfenv-environment-file
fi
