#!/usr/bin/env bash
# Summary: Show the current Cloud Foundry environment
set -e
[ -n "$CFENV_DEBUG" ] && set -x

if [ -z "$CFENV_ENVIRONMENT" ]; then
  CFENV_ENVIRONMENT_FILE="$(cfenv-environment-file)"
  CFENV_ENVIRONMENT="$(cfenv-environment-file-read "$CFENV_ENVIRONMENT_FILE" || true)"
fi

if [ -z "$CFENV_ENVIRONMENT" ] || [ "$CFENV_ENVIRONMENT" = "system" ]; then
  echo "system"
  exit
fi

environment_exists() {
  local environment="$1"
  [ -d "${CFENV_ROOT}/environments/${environment}" ]
}

if environment_exists "$CFENV_ENVIRONMENT"; then
  echo "$CFENV_ENVIRONMENT"
elif environment_exists "${CFENV_ENVIRONMENT#cf-}"; then
  { echo "warning: ignoring extraneous \`cf-' prefix in environment \`${CFENV_ENVIRONMENT}'"
    echo "         (set by $(cfenv-environment-origin))"
  } >&2
  echo "${CFENV_ENVIRONMENT#cf-}"
else
  echo "cfenv: environment \`$CFENV_ENVIRONMENT' is not installed" >&2
  exit 1
fi
